import time

sentences = [
    "The smell of oil prevails throughout.",
    '"....e, com......take....y..eth.."',
    '"sm....to..."',
    '"........nna k...a when........e that, h..."',
    '"...He.....idd.....m ki......"',
    "i call our, but my worlds collapse against the wall.",
    "My body is too soft.",
    "my outline is too blurry.",
    "of course i can't break through.",
    "I'm no more than a shadow.",
    "this world is way too gentle.",
    "it's been too kind",
    "an ungrateful brat",
    "like me.",
    "if you forgot",
    "it probably",
    "didn't matter.",
    "if you forgot,",
    "it probably",
    "wasn't real.",
    "It's like",
    "a dream?",
    "exactly like",
    "a dream.",
    "a bird",
    "flies",
    "past",
    "the",
    "window.",
    "my",
    "eyes",
    "don't",
    "water.",
    '"you',
    "can't",
    "keep",
    "doing",
    'this."',
    "every",
    "man's",
    "an",
    "animal,",
    'yeah?"',
    "when i looked into the mirror i saw...",
    "there",
    "is no",
    "knife.",
    "there",
    "is no",
    "cut.",
    "Z.A.T.O.",
    "I Love the World and Everything In It",
]

for sentence in sentences:
    print(sentence)
    time.sleep(1)
