import time

def ecrire(texte, vitesse=0.5):
    for lettre in texte:
        print(lettre, end='', flush=True)
        time.sleep(vitesse)
    print()

print("The smell of oil prevails throughout.")
time.sleep(1)
print('"....e, com......take....y..eth.."')
time.sleep(1.5)
print('"sm....to..."')
time.sleep(1)
print('"........nna k...a when........e that, h..."')
time.sleep(1)
print('"...He.....idd.....m ki......"')
time.sleep(1)
print("i call our, but my worlds collapse against the wall.")
time.sleep(1)
print("My body is too soft.")
time.sleep(1)
print("my outline is too blurry.")
time.sleep(1)
print("of course i can't break through.")
time.sleep(1)
print("I'm no more than a shadow.")
time.sleep(1)
print("this world is way too gentle.")
time.sleep(1)
print("it's been too kind")
time.sleep(1)
print("an ungrateful brat")
time.sleep(1)
print("like me.")
time.sleep(1)
print("if you forgot")
time.sleep(1)
print("it probably")
time.sleep(1)
print("didn't matter.")
time.sleep(1)
print("if you forgot,")
time.sleep(1)
print("it probably")
time.sleep(1)
print("wasn't real.")
time.sleep(1)
print("It's like")
time.sleep(1)
print("a dream?")
time.sleep(1)
print("exactly like")
time.sleep(1)
print("a dream.")
time.sleep(1)
print("a bird")
time.sleep(1)
print("flies")
time.sleep(1)
print("past")
time.sleep(1)
print("the")
time.sleep(1)
print("window.")
time.sleep(1)
print("my")
time.sleep(1)
print("eyes")
time.sleep(1)
print("don't")
time.sleep(2)
print("water.")
time.sleep(2)
print('"you')
time.sleep(2)
print("can't")
time.sleep(2)
print("keep")
time.sleep(2)
print("doing")
time.sleep(2)
print('this."')
time.sleep(2)
print('every')
time.sleep(2)
print("man's")
time.sleep(2)
print("an")
time.sleep(2)
print("animal,")
time.sleep(2)
print('yeah?"')
time.sleep(2)
print("when i looked into the mirror i saw...")
time.sleep(2)
print("there")
time.sleep(2)
print("is no")
time.sleep(2)
print("knife.")
time.sleep(2)
print("there")
time.sleep(2)
print("is no")
time.sleep(2)
print("cut.")
time.sleep(2)
print("Z.A.T.O.")
time.sleep(2)
print("I Love the World and Everything In It")
time.sleep(2)